- lib/pushy_client.rb
- lib/pushy_client/job_runner.rb
- lib/pushy_client/protocol_handler.rb
Merge preliminary capture output work.
> Implementation of “capture_output” functionality.

- omnibus/config/projects/push-jobs-client.rb
Pinning chef and ohai versions so push-client can
build successfully.
> Pin chef and ohai versions

- omnibus/LICENSE
- omnibus/config/projects/push-jobs-client.rb
- omnibus/config/software/opscode-pushy-client.rb
Adds licenses for any "Unspecified" licenses.
http://manhattan.ci.chef.co/job/push-jobs-client-trigger-ad_hoc/27/downstreambuildview/
> Add licenses

- .travis.yml
- Rakefile
- lib/pushy_client/whitelist.rb
- opscode-pushy-client.gemspec
- spec/spec_helper.rb
Also make the tests pass by:
* Add a default rake task
* Require chef/log in whitelist so it can find the constant
* Add rake as a dev dependency
* Remove rspec deprecation message
> Add travis (and default rake task)

- opscode-pushy-client.gemspec
> Allow for modern Chef and Ohai

- .expeditor/update_version.sh
Signed-off-by: Seth Chisamore <schisamo@chef.io>
> Perform version bump on correct path

- .expeditor/update_version.sh
- Gemfile.lock
- lib/pushy_client/version.rb
Signed-off-by: Seth Chisamore <schisamo@chef.io>
> Ensure version bump sed matches the correct line

- .expeditor/config.yml
Signed-off-by: Tom Duffield <tom@chef.io>
> Update the CHANGELOG when push-client is promoted to stable

- .expeditor/config.yml
- CHANGELOG.md
Signed-off-by: Tom Duffield <tom@chef.io>
> Update Expeditor config to meet 0.5.0 requirements

- Gemfile.lock
- RELEASE_PROCESS.md
- omnibus/.kitchen.yml
- omnibus/Gemfile.lock
- omnibus_overrides.rb
Signed-off-by: Prajakta Purohit <prajakta@opscode.com>
> Updating bundler to 1.15.4. Some README updates.

- lib/pushy_client.rb
- lib/pushy_client/protocol_handler.rb
- omnibus/Gemfile.lock
- omnibus/config/software/opscode-pushy-client.rb
- omnibus_overrides.rb
Signed-off-by: Jeremiah Snapp <jeremiah@chef.io>
> Add AIX support

- lib/pushy_client.rb
This change attempts to address an edge case scenario where the push client
service becomes wedged, presumably after or during a network outage.
Customer logs show the typical retry behavior in `Chef::HTTP` when the `reconfigure`
block executes the `get_config` code path. Afterwards, there seems to be
an infinite deadlock with no further log messages from within the `reconfigure`.
This probably means that the `@reconfigure_lock.synchronize do` block held
onto the mutex lock, began executing the block code but then never released
the lock.
When diagnosing what was happening within that block I noticed the `get_config`
could lead to a behavior of extensive time being spent in HTTP retries during
a network outage. Depending on the situation, if the requests were timing out,
the default value …
> Optimize `get_config` by eliminating extensive retry behavior

- Gemfile
- Gemfile.lock
- opscode-pushy-client.gemspec
Aligns with our other projects and allows us to exclude this in the
appbundler in DK
> Remove rdoc gem and add docs group with yard

- omnibus_overrides.rb
This resolves a CVE and fixes a few bugs
> Update Ruby from 2.4.4 to 2.4.5

- .expeditor/config.yml
- .expeditor/release.omnibus.yml
- omnibus/omnibus-test.ps1
- omnibus/omnibus-test.sh
_This is a release engineering only change._
This replaces the Jenkins omnibus build/test pipeline with Buildkite.
> Replace Jenkins omnibus build/test pipeline with Buildkite

- omnibus/omnibus-test.sh
Fix signed omnibus package test so it references the correct variable.
> Fix signed omnibus package test

- README.md
Signed-off-by: Mark Anderson <mark@chef.io>
Add project state info as per https://github.com/chef/chef-oss-practices/blob/master/repo-management/repo-states.md
> Update with OSS Practices information

- omnibus/config/projects/push-jobs-client.rb
Signed-off-by: Seth Chisamore <schisamo@chef.io>
> Begin signing MSI's with renewed Windows Signing Cert

- .expeditor/release.omnibus.yml
Signed-off-by: Jaymala Sinha <jsinha@chef.io>
> Add Aix 7.2 platform

- .expeditor/release.omnibus.yml
Signed-off-by: Jaymala Sinha <jsinha@chef.io>
> Deprecate macOS 10.12 and add macOS 10.15 support

- .expeditor/config.yml
- .expeditor/release.omnibus.yml
- RELEASE_NOTES.md
- RELEASE_PROCESS.md
Platforms have changed significantly since the last release.
So has the release process.
> Update release notes, process, platforms.

- lib/pushy_client/cli.rb
Signed-off-by: Kapil Chouhan <kapil.chouhan@msystechnologies.com>
- Minor fixes.
Fixes: #186
> Fix for file_dir option
