lib/pushy_client.rb
lib/pushy_client/job_runner.rb
lib/pushy_client/periodic_reconfigurer.rb

The periodic reconfigurer can cause running jobs to terminate early; this should mitigate but not outright fix the issue.
This is a minimal change fix that delays reconfiguration until any running jobs have terminated. However this does have some race conditions, in that
1) The reconfigure is delayed by polling on idle; however we don't block the acceptance of a new job immediately after reconfiguration, and that job may be terminated
2) A new job may be started before the poller recognizes that the old job 
Fixes #69

Fix for periodic reconfigure causing early termination

---

omnibus/Gemfile.lock
omnibus/config/projects/push-jobs-client.rb

This allows master to build at chef/omnibus-software#556

Allow recent omnibus-software ruby version convention.

---

lib/pushy_client/protocol_handler.rb

Buffering heartbeats can cause trauma on the server after restart.
Related to these PRs:
https://github.com/chef/omnibus-pushy/pull/92
https://github.com/chef/oc-pushy-pedant/pull/54
https://github.com/chef/opscode-pushy-client/pull/84

Don't buffer more than a few heartbeats

---

lib/pushy_client.rb
lib/pushy_client/windows_service.rb

Replaced Chef::REST with Chef::ServerAPI in pushy_client
Prefer Chef::HTTP::SimpleJSON over Chef::REST in windows_service
Use get instead get_rest in pushy_client

Chef::REST optimizations

---

CHANGELOG.md
lib/pushy_client.rb
lib/pushy_client/protocol_handler.rb
lib/pushy_client/version.rb
omnibus/config/projects/push-jobs-client.rb

Do not enforce 2.x reconfigure protocol on clients that have fallen back to 1.x
Fixes #94 & SPOOL-306

Fix Reconfigure Loops for 2.x clients using 1.x connection protocol

---

lib/pushy_client/cli.rb

You can't trap SIGKILL (kill -9), but previously it was ignored, now it gives
an EINVAL error preventing push jobs client from starting.

Change sigkill handler to sigint

---

.chef/client.rb
.chef/knife.rb
.chef/push-jobs-client.rb
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
.gitignore
README.md
lib/pushy_client/protocol_handler.rb
lib/pushy_client/version.rb

In cases where the Push Jobs Client loses connectivity to the Push Jobs Server, it can enter into a reconfigure loop causing an exponential increase in threads ultimately leading to the server falling over because Ruby has consumed all the resources. By breaking out of the protocol handler loop after triggering the reconfigure, the thread count now grows linearly (one thread per reconfigure) instead of exponentially. Completely avoiding the thread growth entirely would require more a more complex and time consuming rewrite.

Address exponential thread increases

---

omnibus/acceptance/.chef/knife.rb
omnibus/acceptance/.kitchen.yml
omnibus/acceptance/Berksfile
omnibus/acceptance/Berksfile.lock
omnibus/acceptance/Makefile
omnibus/acceptance/README.md
omnibus/acceptance/metadata.rb
omnibus/acceptance/recipes/chef-server-user-org.rb
omnibus/config/projects/push-jobs-client.rb
opscode-pushy-client.gemspec

Chef 12.8.1 has a loose gem constraint, which will cause two versions of
ohai to be installed. This results in push-jobs throwing an error if a
newer version of Ohai than the one push-jobs uses is ever installed.
Until we upgrade Chef to a more modern version, have the gem use the
same constraints as the chef gem, and do not override the omnibus
version of the gem installed.
* #109 
* Chef COOL-614
Signed-off-by: Tom Duffield <tom@chef.io>

Fix ohai gem constraints

---

omnibus/config/projects/push-jobs-client.rb

Signed-off-by: Tom Duffield <tom@chef.io>
Pin Push Client to latest Ohai 8.x (now that Ohai is v13 on master).
* Broken Jenkins Builds

Pin ohai to 8.23.0 as chef/ohai master is now 13

---

.gitignore
.travis.yml
CHANGELOG.md
Gemfile.lock
lib/pushy_client/version.rb
omnibus/Gemfile
omnibus/Gemfile.lock
omnibus/config/projects/push-jobs-client.rb
omnibus/config/software/opscode-pushy-client.rb
opscode-pushy-client.gemspec

The hard dependencies on old Chef, Ruby, and Ohai are causing significant problems for building standalone and in ChefDK. This modernizes the Chef, Ohai, and Ruby that we are using. 
Note: We're not updating to 2.3.1 in the standalone package because that would require us to move to some very nasty long-lived branches of omnibus and omnibus-software. So, instead, we're sticking with 2.2.6 until things settle down. That being said, I did add 2.3.1 to Travis so we can start catching some failures.

Update to modern dependencies

---

Gemfile.lock
omnibus/config/projects/push-jobs-client.rb

Signed-off-by: Kartik Null Cating-Subramanian <ksubramanian@chef.io>
We need bundler > 1.14 to allow non-windows platforms to build under omnibus.  Otherwise they fail trying to install win32-* gems.

Allow non-win platforms to build again.

---

omnibus/config/projects/push-jobs-client.rb

The cert has been updated as the old one expires on 2017-07-25.
Signed-off-by: Seth Chisamore <schisamo@chef.io>

Update SHA1 fingerprint for MSI signing cert

---

lib/pushy_client/windows_service.rb
omnibus/.kitchen.yml
omnibus/Gemfile.lock
omnibus/config/projects/push-jobs-client.rb
omnibus/config/software/opscode-pushy-client.rb
omnibus/resources/push-jobs-client/msi/source.wxs.erb
omnibus_overrides.rb

See chef/omnibus-software#830 for details.  Don't merge until that goes in.
Also updates .kitchen.yml to build windows-2012r2 because we don't use win 2008 builders in the CI anymore.
Resolves #125 (I hope :-P)

Allow push jobs to build libzmq from source on windows

---

Gemfile.lock
omnibus/Gemfile.lock
omnibus_overrides.rb

Signed-off-by: Prajakta Purohit <prajakta@opscode.com>
Update ruby to 2.4.2
https://www.ruby-lang.org/en/news/2017/09/14/webrick-basic-auth-escape-sequence-injection-cve-2017-10784/

Update ruby to 2.4.2

---

lib/pushy_client/periodic_reconfigurer.rb
lib/pushy_client/protocol_handler.rb

WIP, for reference and commentary as I have done ZERO TESTING on this.
This modifies the periodic reconfigure loop to allow us to alter the
reconfigure timeout, and makes packet send timeouts advance the reconfigure deadline.
It seems probable if we are timing out in zeromq, we have a broken
connection (as if we failed to recieve heartbeats) and should treat it
the same way.
Signed-off-by: Mark Anderson <mark@chef.io>

Quick hack at a reconfigure strategy

---

lib/pushy_client.rb
lib/pushy_client/periodic_reconfigurer.rb
lib/pushy_client/protocol_handler.rb

Signed-off-by: Nolan Davidson <ndavidson@chef.io>
As noted in #123, the push jobs client will sometimes hang on the
send_string call when the push jobs server is restarted (or is replaced
by another PJ server).  After adding this timeout, I have been able to
successfully restart and replace the PJ server without the client
hanging consistently.
#123

Wrap ZMQ request in timeout

---

.expeditor/update_version.sh

bundler is buggy and is crashing on `bundle update opscode-pushy-client`
right now with:
```
% bundle update opscode-pushy-client
Fetching gem metadata from https://rubygems.org/........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "win32-api":
In snapshot (Gemfile.lock):
win32-api (= 1.5.3)
In Gemfile:
win32-api x86-mingw32
windows-pr x86-mingw32 was resolved to 1.2.6, which depends on
win32-api (>= 1.4.5)
Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```
which is incorrect, because win32-api 1.5.3 is >= 1.4.5.

expeditor config: bundle update every time

---

.expeditor/config.yml

We were missing some configs around skipping all as well, which is a very useful label to use.

Expeditor: use our standard labels and auto delete branches

---

.github/PULL_REQUEST_TEMPLATE.md
.github/lock.yml

The changelog is auto managed so we don't want people to update that.

Add the github lock bot and fix the PR template

---

omnibus/Gemfile.lock

https://github.com/chef/opscode-pushy-client/pull/163 needed omnibus-software bumped to get the latest definition for Ruby 2.4.5 and we missed it.

Bump omnibus-software for latest ruby

---

.chef/push-jobs-client.rb
lib/pushy_client.rb
lib/pushy_client/cli.rb
lib/pushy_client/protocol_handler.rb
spec/pushy_client/protocol_handler_spec.rb

Provide option that user can configure the max_body_size in `push-jobs-client.rb`. Default max_body_size is `63000`, also user can provide options as `--max-body-size` at runtime.
Signed-off-by: piyushawasthi <piyush.awasthi@msystechnologies.com>

MSYS-832 - Added feature that end user can configure STDER/STDOUT size

---

.travis.yml
Gemfile.lock
omnibus/Gemfile.lock
omnibus_overrides.rb
opscode-pushy-client.gemspec

Remove support for Chef 12 and Ruby 2.2/2.3.

Require Chef 13 or later and allow Chef 15

---

opscode-pushy-client.gemspec

Slim down the files we ship in the gem artifact to just what we need to build and test the client. This takes the gem artifact from 794 KB to 28k.

Don't ship omnibus files in the gem artifact

---

.expeditor/config.yml

If there is no top level 'promote' key then expeditor will default to:
`- built_in:promote_artifactory_artifact`
But we have a promote key here and are lacking that action. This adds it.

Expeditor should push omnibus packages through artifactory

---

Gemfile
Gemfile.lock

We don't need this in the omnibus packages since we don't actually use
it anywhere in our ecosystem.

Remove the unused windows-api gem

---

omnibus/omnibus-test.ps1
omnibus/omnibus-test.sh

This just updates the `omnibus-test.*` scripts to use tools that have been moved into the omnibus-toolchain. It also makes some changes to output to be more consistent across our omnibus projects.

Use new omnibus-toolchain scripts in omnibus-test.* scripts

---

.expeditor/release.omnibus.yml
RELEASE_PROCESS.md
omnibus/.kitchen.yml
omnibus/README.md
omnibus/acceptance/.kitchen.yml
omnibus/acceptance/Makefile

Signed-off-by: Christopher A. Snapp <csnapp@chef.io>
Deprecate Ubuntu-14

Deprecate Ubuntu-14

---

.expeditor/release.omnibus.yml

Signed-off-by: Jaymala Sinha <jsinha@chef.io>
Enable RHEL8, Windows 2016 and Windows 2019 packages

Enable RHEL8 Windows 2016 and Windows 2019 packages

---

.expeditor/release.omnibus.yml
omnibus/Gemfile
omnibus/Gemfile.lock

This change only affects CI. A new version of omnibus is required and the artifactory gem is required for the publish part of the build stage. Platform names in `release.omnibus.yml` are also fixed to conform with what the new package publishing code in the omnibus gem expects.
https://github.com/chef/omnibus-buildkite-plugin/issues/22

[ci] Fix omnibus pipeline

---

omnibus/Gemfile.lock
omnibus_overrides.rb

Update Gemfile.lock and remove libsodium pinning

Update Gemfile.lock and remove libsodium pinning
